#/usr/bin/env make

BUILD_DIR := build
Q :=

$(BUILD_DIR):
	$(Q)mkdir -p $(BUILD_DIR)

include maketools/help.mk
include maketools/docker.mk
include maketools/cwdapache.mk
include maketools/apache.mk
